name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, gd, pdo, pdo_mysql

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install NPM deps and build
        run: |
          npm ci
          npm run build

      # 🔑 Generate SQL dari migration + seeder
      - name: Run migrations locally
        run: |
          php artisan migrate --force

      - name: Create deployment package
        run: |
          zip -r deploy.zip . \
            -x "node_modules/*" \
            -x "storage/logs/*" \
            -x "public/build/*"

      # Debug: cek apakah deploy.zip ada
      - name: Check deploy.zip exists
        run: ls -lah

      - name: Move deploy.zip to dist folder
        run: |
          mkdir dist
          mv deploy.zip dist/

      - name: 📂 Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./dist/
          server-dir: ${{ secrets.FTP_DIR }}
          exclude: |
            *
          include: |
            deploy.zip

      - name: Run deploy script With Shell 3
        run: curl "https://aissystem.org/deployscript/deploy.php?token=Lagis3nt0s@"

      - name: Set Default User
        run: php artisan make:filament-user --name="Super Admin" --email=admin@aissystem.org --password=ais123AIS
        
