name: Deploy Laravel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl, pdo_mysql
          coverage: none

      # 3. Composer install
      - name: Install Composer dependencies
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      # 4. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm ci

      - name: Build frontend assets
        run: npm run build

      # 5. Check storage link
      - name: Ensure storage link exists
        run: |
          if [ ! -L "public/storage" ]; then
            php artisan storage:link
          fi

      # 6. Fix permissions sesuai standar Laravel (runner)
      - name: Fix file permissions
        run: |
          find . -type f -exec chmod 644 {} \;
          find . -type d -exec chmod 755 {} \;
          chmod -R ug+rwx storage bootstrap/cache

      # 7. Deploy via FTP
      - name: 📂 Deploy to FTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: ./
          remote_path: ${{ secrets.FTP_DIR }}
          delete_remote_files: false
          exclude: |
            **/node_modules/**
            **/tests/**
            **/.git*
            **/storage/logs/**
