name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, curl, intl, mysql
          tools: composer

      # 3. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 4. Make bash file executable
      # - name: Make deploy.sh executable
      #   run: chmod +x /home/aisk7155/public_html/deployscript/deploy.sh

      # 4. Run bash script
      - name: Run deploy script With Shell 3
        run: curl "https://aissystem.org/deployscript/deploy.php?token=Lagis3nt0s@"
