name: 🚀 Deploy Laravel ke Shared Hosting

on:
  push:
    branches:
      - main  # branch yang memicu deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Install PHP dependencies (Composer) di GitHub Actions
      - name: Install PHP dependencies
        run: |
          composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      # 3️⃣ Build frontend assets (npm / Vite / Laravel Mix)
      - name: Build frontend assets
        run: |
          npm ci
          npm run build

      # 4️⃣ Install lftp
      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      # 5️⃣ Upload semua file yang diperlukan ke shared hosting
      - name: Deploy via FTP (incremental)
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -u $FTP_USER,$FTP_PASSWORD $FTP_HOST <<EOF
          set ftp:ssl-allow no
          
          # Upload incremental: file baru atau diubah
          mirror -R --only-newer --parallel=5 --verbose \
            --exclude .git/ \
            --exclude .github/ \
            --exclude node_modules/ \
            ./ /public_html/
          quit
          EOF
      - name: Run deploy script With Shell
        run: curl "https://aissystem.org/deploy.php?token=Lagis3nt0s@"